#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N fastqcT
#
# Send an email after the job has finished
#$ -m e
#$ -M andyszermeno@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load fastqc/0.11.3
#
# Write your commands in the next line
cd /mnt/Guanina/bioinfo24/Equipo3/Proyecto/TRIM_results
for file in /mnt/Guanina/bioinfo24/Equipo3/Proyecto/TRIM_results/*.fq.gz; do fastqc $file -o /mnt/Guanina/bioinfo24/Equipo3/Proyecto/quality2; done
